### PR TITLE
OpenVINO 2024.0.0

### PR DESCRIPTION
**Pull request by dkurt**
related: https://github.com/opencv/opencv/pull/25199

### CODE REVIEW

**Comment by fengyuentau** [comment]
Does this version work with existing `ngraph::` namespace? If not, I guess we need a transition in https://github.com/opencv/opencv/pull/25199, merge it and then merge this version upgrade to avoid breaking CI.

**Comment by dkurt** [comment]
@fengyuentau, good point! Well, at least we can create a docker image to test https://github.com/opencv/opencv/pull/25199

**Comment by fengyuentau** [comment]
I tried to build a new image on quay.io but failed. Lets wait for Alexander coming back.

**Pull request merged**
