### PR TITLE
Added pull handling for docker images

### PR DESCRIPTION
**Pull request by asenyaev**

### CODE REVIEW

**Comment by asenyaev** [comment]
cc @alalek @fengyuentau

**Comment by fengyuentau** [comment]
Could you kindly provide some examples to explain why we need this and why it should be set false?

**Comment by asenyaev** [comment]
@fengyuentau I added it in case of these failures: 
1. https://github.com/opencv/opencv/runs/7076063907?check_suite_focus=true#step:7:37
2. https://github.com/opencv/opencv/runs/7086789281?check_suite_focus=true#step:8:19

It set it to `false`, because it's the default strategy for merging.

**Review by fengyuentau — APPROVED** [review]
Thanks a lot for the explanation. I also met this issue in my pull requests.

**Pull request merged**
