### PR TITLE
RISC-V: updated image for RVV 0.7.1 to use 2.8.0 toolchain

### PR DESCRIPTION
**Pull request by mshabunin**
Preparation to switch weekly build to 2.8.0 Xuantie toolchain. Related PR: https://github.com/opencv/opencv/pull/24841

Published: `quay.io/opencv-ci/opencv-ubuntu-22.04-riscv-071:20240117`

### CODE REVIEW

**Comment by opencv-alalek** [comment]
> to use 2.6.0 toolchain

2.8.0?

**Comment by mshabunin** [comment]
> 2.8.0?

Sure :facepalm:

**Comment by opencv-alalek** [comment]
commit message too

**Comment by mshabunin** [comment]
Fixed. Thank you.

**Review by opencv-alalek — APPROVED** [review]

**Pull request merged**
